version: "3"
services:
  web:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - net
    hostname: web
    volumes:
      - geodata:/app/data
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: 'redis:7-alpine'
    restart: always
    user: redis
    volumes:
      - redis-data:/data
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  net:
volumes:
  geodata:
  redis-data:
