# fly.toml app configuration file generated for postal-codes on 2023-04-20T10:10:08-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "postal-codes"
primary_region = "lax"

# [mounts]
# source = "postal_codes_data"
# destination = "/app/data"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
# min_machines_running = 1

[[http_service.checks]]
interval = "60s"
timeout = "2s"
grace_period = "5s"
path = "/health/"
method = "GET"

[checks]
[checks.alive]
type = "tcp"
interval = "15s"
timeout = "2s"
grace_period = "5s"

[env]
# TINI_SUBREAPER = ""
